import React, { PureComponent } from "react";
import PropTypes from "prop-types";
import { withRouter } from "react-router-dom";
import { Message, Icon, Header as Heading } from "semantic-ui-react";

import XKCD_COMIC from "Common/assets/password_strength.png";

import withStyles from "Common/components/withStyles";
import stylesGenerator from "./styles";

class AboutView extends PureComponent {
  static propTypes = {
    computedStyles: PropTypes.shape({
      comic: PropTypes.string.isRequired,
      messageBody: PropTypes.string.isRequired
    }).isRequired,
    history: PropTypes.objectOf(PropTypes.object).isRequired,
    isLoading: PropTypes.bool.isRequired,
    actions: PropTypes.shape({
      emitIsLoading: PropTypes.func.isRequired
    }).isRequired
  };

  contactHandler = () => {
    const { isLoading, actions, history } = this.props;
    actions.emitIsLoading({ isLoading: !isLoading });
    history.push("/contactUs");
  };

  render() {
    const { computedStyles } = this.props;

    return (
      <div>
        <Heading as="h3">
          A password generator based on{" "}
          <a
            href="https://xkcd.com/936/"
            rel="noopener noreferrer"
            target="_blank"
          >
            xkcd 936
          </a>
        </Heading>
        <Message info>
          <Message.Header>
            <Icon name="github" size="big" />
            Find Us On GitHub
          </Message.Header>
          <div className={computedStyles.messageBody}>
            <p>
              <Icon name="code branch" size="large" />
              <a
                href="https://github.com/joshghent/password/branches"
                rel="noopener noreferrer"
                target="_blank"
              >
                Branches
              </a>
            </p>
            <p>
              <Icon name="bug" size="large" />
              <a
                href="https://github.com/joshghent/password/issues"
                rel="noopener noreferrer"
                target="_blank"
              >
                Issues
              </a>
            </p>
            <p>
              <Icon name="users" size="large" />
              <a
                href="https://github.com/joshghent/password/graphs/contributors"
                rel="noopener noreferrer"
                target="_blank"
              >
                Contributors
              </a>
            </p>
          </div>
        </Message>
        <Message warning>
          <Message.Header>Passwords</Message.Header>
          <p>
            Generated passwords are NOT and will NEVER be stored on our servers
            or anywhere else.
          </p>
        </Message>
        <Message warning>
          <Message.Header>Disclaimer</Message.Header>
          <p>
            We have no claim for the passwords generated to be cryptographically
            secure. We do not take responsiblity for any identity theft or any
            other bad things that may arise from using passwords generated by
            this application. Use at your own risk.
          </p>
        </Message>
        <img className={computedStyles.comic} src={XKCD_COMIC} alt="xkcd-936" />
      </div>
    );
  }
}

export default withRouter(withStyles(stylesGenerator)(AboutView));
